language: node_js

sudo: false

node_js:
  - '7'

script:
  - npm run setup
  - npm run endpoint

deploy:
  provider: s3
  access_key_id:
    secure: BsBjAcRtYZGyYDkulgxykIFqVOhlmIyIroOFrZZ/uI3WBzQHon45I0PVLtKoB4uAyeNkFm84GRVVz4o7gdjT07GakEG4yYpRbmAKKnMEF4jh+kLZaFvB8VhxvhyF6rVSrv+SKC3lyyNozufG2906u7Ndf72rhZYtHp87uNqPsx4x3CqIB81vebufMpHesTKRFvu17XAIYOumbJO7uXkYtYKKfl2tPnMKedP+OZ74tzyYLtZewzrC50UT1+33SPJGUR88p8p7QmIRZs6CsLqwGTvAy+RlZcJYgjJ6UrwQBjNmAMzZ2xzzBKbo8w6mj9k33q4cx9eddv6WtRVBYdWC57J4BLTq/+olMYScDiJ+GNRMxCq7uhKTlRe/IdNaBB3ede0RK7zU2x3jg+zUgWrf4KzEb34/msn0UwhvfQK2eE93R41DvBO5EH0St3NjaXFVnCa9esaGFSaPKxBdL6Kc1vmjz5j6CPfqGB6h4cq2MRhfpQ56nRNK2z5RUIh8ew0XwX1e45oaRu/Qj/7BZNMDFwu6dmPBTRK23Wh6qHSfINOFxaIwzp02I694wmwnFIqxczFHUHwcGmFZ0fQM4J56/F2DYFM5HQIX2jZgcAsMbCDz2jHQFJK0GyI0J4LdiaSIbsi2A79ebHZn0Z5rsyCVBQoKER762bzbOphtNO1kSgA=
  secret_access_key:
    secure: syR/GE4EWOgfcG0QKLEzrhGtw8G40w/FjMCDaNdge39rFu9YKpoH8cKCfc4vmr+gntLv5MIJPEh5gHERfa/CDnFqrInY7N1iM4cPzNb3W/jMWodXXNn4v4TC5rKpEgZ4IvZ8AqN5EqEngA2F1+HInoD8m6JJbSh4KDxQX1hz9sopsMZeOu00xv3RioLI7uWxz/IdRxwjFReoQV652f6H/JldzUTB23KymWQd5QBUzW/ul291XLsrn0FvLCqvNc2LitAXkkJWPbsHw2Xj86ksE5V6QFkm8t3nwXMGx5V7NB5k7KJNn6aMEgshnZ6XbDJ+l/12EMFKKJMouRqp48b4e+5XC4nGOTqsR0ZiI/OlIMO0hbWY+rv0V/Y1o8siKK3gDnVzQ5oCmbd6SzcmQ4v41bLME/6E1huS1ns1oX6Tqx773sDodtHMWVnOFJ3fXtCeOEf1Tl3vxrVHvJWqRB81W3nlCyMRYpBpsFKbsEntgVM5oWMYx6V0vOd5sv4txwjrbRzCnIRkpo8Wm1MWNERNU7gWkUbKZ0eonTaGucg8fRieDZBKe63A5MRCJj6Rxjzg9te5fx9Im6uVhhPCtJQhTE0eSatsSFywgIgchT17fMMVEVkk3l+YSQPJy1LVO6aT9tpM7utVGD0ViiWmj1XbZRLsGUEC+GyjI90el2YUUes=
  bucket: bav-mirador-demo
  skip_cleanup: true
  acl: public_read
  region: us-east-1

notifications:
  email: false
